# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        uses: ./.github/workflows/build.yml